services:
    
    gunicorn:
        image: python:3.11
        command: sh -c "python -m venv venv && . venv/bin/activate && pip install gunicorn && cd gunicornapp && gunicorn main:app --bind 0.0.0.0:8000"
        ports:
            - "8000:8000"
        volumes:
            - ./main.py:/gunicornapp/main.py

    nginx:
        image: nginx:1.21.3
        ports:
            - "8080:8080"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - .:/etc/public/
        depends_on:
            - gunicorn